
---
title: "NY_NOAA dataset"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---



```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(p8105.datasets)

```


```{r}

set.seed(1)

ny_noaa_df = ny_noaa %>%
  mutate(year = lubridate::year(date),
         month = lubridate::month(date),
         day = lubridate::day(date)) %>%
  mutate(tmin = as.numeric(tmin) / 10 * (9 / 5) + 32, tmax = as.numeric(tmax) / 10 * (9 / 5) + 32) %>%
  mutate(snwd = (as.numeric(snwd) / 10) / 2.54, snow = (as.numeric(snow) / 10) / 2.54) %>%
  mutate(prcp = (as.numeric(prcp) / 100) / 2.54) %>%
  mutate(snow = ifelse(snow < 0, NA, snow)) %>%
  mutate(month = month.abb[month]) %>%
  mutate(month = factor(month, 
                        levels = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))) %>%
  sample_n(10000)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A
```{r}
ny_noaa_df %>%
  plot_ly(x = ~tmin, y = ~tmax, type = "scatter", color = ~month, mode = "markers",
          alpha = .5,
          text = ~date,
          colorscale='Viridis') %>%
  layout(title = "Min vs. Max Temperatures in NY from 1981-2010",
         xaxis = list(title = "Min Temperature (Degrees F)", autotick = F, dtick = 10),
         yaxis = list(title = "Max Temperature (Degrees F)"))
```




Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
#average yearly snowfall over time

ny_noaa_df %>% 
  filter(snow != 0) %>%
  group_by(year) %>%
  summarize(mean_snowfall = mean(snow, na.rm = TRUE)) %>%
  plot_ly(x = ~year, y = ~mean_snowfall, type = "scatter", mode = "lines",
          alpha = .5) %>%
  layout(title = "Yearly Mean Snowfall from 1981-2010",
         xaxis = list(title = "Year", tickangle = -45, dtick = 2),
         yaxis = list(title = "Mean Snowfall (inches)"))

  





```

### Chart C

```{r}

#boxplots for distribution of max temperatures on days when it snowed and didn't snow in dec - march 

ny_noaa_df %>%
  filter(month %in% c("Mar", "Feb", "Jan", "Dec")) %>%
  mutate(Snow_Status = ifelse(snow > 0, "Snowfall Day","No Snowfall Day")) %>%
  plot_ly(x = ~Snow_Status, y = ~tmax, color = ~Snow_Status, type = "box") %>%
  layout(title = "Max Daily Temp Dec-Mar by Snowfall Status",
         yaxis = list(title = "Max Daily Temperature"))
  



```

